import Head from "next/head";
import {SignInButton, useUser} from "@clerk/nextjs";
import Image from "next/image";

import {api, type RouterOutputs} from "~/utils/api";

import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
dayjs.extend(relativeTime);

type PostWithAuthor = RouterOutputs["posts"]["getAll"][number];
export function PostView(props:PostWithAuthor){
    const {post, author} = props;
    return (
        <div
            key={post.id}
            className="flex p-4 border-b border-slate-400 gap-3">
            <Image
                src={author.imageUrl}
                alt={`@${author.username}'s profile picture`}
                className="w-14 h-14 rounded-full"
                width={56}
                height={56}
            />
            <div className="flex flex-col">
                <div className="flex gap-1 text-slate-300 font-bold">
					<span>{`@${author.username}`}</span>
                    <span className="mx-1">·</span>
                    <span className="font-thin">{`${dayjs(post.createdAt).fromNow()}`}</span>
                </div>
                <span>{post.content}</span>
            </div>
        </div>
    );
}

export function CreatePostWizard(){
    const {user} = useUser();

    if(!user) return null;

    return (
        <div className="flex gap-3 w-full">
            <Image
				src={user.imageUrl}
                alt={`@${user.username}'s profile picture`}
                className="w-14 h-14 rounded-full"
                width={56}
                height={56}
            />
            <input
                placeholder="Type some emojis!"
                className="bg-transparent grow outline-none"
            />
        </div>
    );
}

export default function Home() {

  const user = useUser();

  const {data, isLoading} = api.posts.getAll.useQuery();

  if(isLoading) return (<div>Loading...</div>);

  if(!data) return (<div>No data</div>);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
          <div className="w-full md:max-w-2xl border-slate-400 border-x">
            <div className="flex border-b border-slate-400 p-4">
                {!user.isSignedIn && (
                    <div className="flex justify-center">
                        <SignInButton />
                    </div>
                )}
                {!!user.isSignedIn && <CreatePostWizard />}
            </div>
            <div className="flex flex-col">
                {[...data, ...data]?.map((fullPost) => (
                    <PostView {...fullPost} key={fullPost.post.id}/>
                ))}
            </div>
          </div>
      </main>
    </>
  );
}
